name: GitHub Actions Demo
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Run unit tests
        run: |
          make test
      - name: Compute code coverage
        run: |
          pip3 install coverage
          make cover